M48
; DRILL file {KiCad (6.0.11-0)} date Friday, 05 May 2023 at 09:17:27
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-05-05T09:17:27+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11-0)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.700
%
G90
G05
T1
X120.058Y-91.475
T2
X113.03Y-114.459
X127.0Y-114.459
T0
M30
